name: Build image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        default: "latest"
  push:
    branches:
      - 'main'
      - 'master'
      - 'release*'
    tags:
      - 'v*'

jobs:
  buildx:
    runs-on: self-runner-extensions
    env:
      GOPATH: /home/runner/work/applicationset
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prepare
        run: |
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.tag }}
          fi
          echo ::set-output name=version::${VERSION}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/kubesphere/argocd-applicationset
          tags: ${{ steps.prepare.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          load: false
          platforms: linux/amd64,linux/arm64